##################################################################################################
## 
##  Xilinx, Inc. 2010            www.xilinx.com 
##  周二 四月 17 09:22:22 2018
##  Generated by MIG Version 4.0
##  
##################################################################################################
##  File name :       example_top.sdc
##  Details :     Constraints file
##                    FPGA Family:       KINTEX7
##                    FPGA Part:         XC7K410TFFG900_PKG
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         0 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41K512M8XX-107
## Data Width: 8
## Time Period: 2500
## Data Mask: 1
##################################################################################################

create_clock -period 5 [get_ports c0_sys_clk_i]
          
############## NET - IOSTANDARD ##################



##################################################################################################
## Controller 1
## Memory Device: DDR3_SDRAM->Components->MT41K512M8XX-107
## Data Width: 8
## Time Period: 2500
## Data Mask: 1
##################################################################################################

create_clock -period 5 [get_ports c1_sys_clk_i]
          
############## NET - IOSTANDARD ##################



##################################################################################################
## Controller 2
## Memory Device: DDR3_SDRAM->Components->MT41K512M8XX-107
## Data Width: 8
## Time Period: 2500
## Data Mask: 1
##################################################################################################

create_clock -period 5 [get_ports c2_sys_clk_i]
          
############## NET - IOSTANDARD ##################


